language: php
php:

  - '7.4'
env:
  - SYMFONY_VERSION="5.1.*" DB=mysql
# Update composer
before-install:
  - composer self-update
# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test
  

script:
  - composer install
  - ./bin/phpunit

