<?php

namespace ContainerF2mmpiH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiipTestFixtures_ServicesDatabaseBackup_MongodbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'liip_test_fixtures.services_database_backup.mongodb' shared service.
     *
     * @return \Liip\TestFixturesBundle\Services\DatabaseBackup\MongodbDatabaseBackup
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/Services/DatabaseBackup/DatabaseBackupInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/Services/DatabaseBackup/AbstractDatabaseBackup.php';
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/Services/DatabaseBackup/MongodbDatabaseBackup.php';

        return $container->services['liip_test_fixtures.services_database_backup.mongodb'] = new \Liip\TestFixturesBundle\Services\DatabaseBackup\MongodbDatabaseBackup($container, ($container->services['liip_test_fixtures.services.fixtures_loader_factory'] ?? $container->load('getLiipTestFixtures_Services_FixturesLoaderFactoryService')));
    }
}
