<?php

namespace ContainerF2mmpiH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiipTestFixtures_Services_FixturesLoaderFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'liip_test_fixtures.services.fixtures_loader_factory' shared service.
     *
     * @return \Liip\TestFixturesBundle\Services\FixturesLoaderFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/Services/FixturesLoaderFactory.php';

        return $container->services['liip_test_fixtures.services.fixtures_loader_factory'] = new \Liip\TestFixturesBundle\Services\FixturesLoaderFactory($container, ($container->privates['doctrine.fixtures.loader'] ?? $container->load('getDoctrine_Fixtures_LoaderService')));
    }
}
